dist: xenial

language: python

python:
  - 3.6

env:
  - PIPENV_VERBOSITY=-1

install:
  - pip install --upgrade pip
  - pip install -U pipenv
  - pipenv install --dev -e .

script:
  - pipenv run python --version

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: robertodr
  password:
    secure: YeQsvLJqmYj7DozUEOeSczZfv6nqeGKu1TOW9BHnumLtCM7lZt1QY3YRliVqc3wqs0FNwpnQqusIBNY4PX+velpKsysNdY/NDQSwzL7fPq2BfLfrRx3TFeF6OOro6lq94lAZvljq59kb6dTYZu8mFhJ2EBoE+/cYuA4aPFfti7YtbIp8izYQDbDusYSNkX0iyn8ZtYPJl3ieApQ18b7oaXV2TTUuCtD/0HgUetPkBcSJs4Oyiw3cm0IEuRujWyD56liyc6zFAurJSk3SXHmZ65RVjlncKsHwVbKpeT/Nrb0ypIuAr21lkYm375lfPCTu03i/zpwoJNwx8D8BGq5JAGD3SY9DyZR2uZ5Bc9/4o5qAWBqVOdNPR00aeyZ9C97DVVGWhuh8rfQOhkWj+oAt4v/jFHISgqe0AEyMlX/2E0Kk1YIsItLyvByQhoi4cmFxGtEuW+m2npUgm4BsCaaF0i9CVyoOkA/cTY/GZAT5bLSavI+pLOQhlA+vozuWgKiLAR34Xw79fKGbB3ZAC0EQyYqle41HIklKHtafyA2AayCvYuTQStOaXcp3q6nwKwqBiqd+suwKUeY4C1Yimal98MtAxcMbcoIgQeAs40sy2H4oexv1VT15fPV1U0kQL6sMuQlh2cKf9aG1veByPVIJPBzFo1heP6FM8nfpkZ8ZrIA=
  on:
    tags: true
    repo: dev-cafe/travis-deploy-to-pypi
    python: 3.6
